### ISSUE TITLE
Is this right?

### ISSUE THREAD

**Issue by joshuazweig** [cs3157/recitations#110]
Can't you just directly modify the pointers of prevNode? Why do you need to search the list? 

https://github.com/cs3157/recitations/blob/master/H-Linked-Lists/linked-lists.md#adding-a-node-after-another-node

**Comment by kevin1** [comment]
I think you're right - if the library trusts that prevNode is already in the list, it shouldn't search. In fact that's what the solution does.

**Comment by j-hui** [comment]
there's actually no point in having the `struct List *list` parameter in the first place, right?

Linux's `list.h` certainly doesn't need it: http://lxr.free-electrons.com/source/include/linux/list.h#L76

**Comment by danhcole** [comment]
>
> If prevNode is NULL, this function should behave just like addFront.


You need to know the list head in this case.

Linux's list implantation is a bit different than what we do in AP, and
doesn't have a separate List type, nor a concept of "add front".

**Comment by kl2792** [comment]
I suppose you can choose to implement custom undefined behavior if the `Node` is not contained in the List

**Comment by danhcole** [comment]
To answer @joshuazweig , no, you don't need to search, but yes, you do need the `struct List` if you need to handle the case where `prevNode == NULL`

@kl2792 I'm not sure what you mean by "if the `Node` is not contained in the `List`"?

**Comment by joshuazweig** [comment]
Submitting a PR to get rid of it.

**Comment by joshuazweig** [comment]
Fixed
