### ISSUE TITLE
I-Debugging-GDB/gdb.md a possible typo

### ISSUE THREAD

**Issue by merlinyx** [cs3157/recitations#114]
Between **Memory Errors** and **Lost Memory**, there's this sentence: 

> The compiler won't warn you about it in any non-trivial case. 

It seems that it should be "the compiler will warn you...".

**Comment by kevin1** [comment]
The full context is:

> What are examples of this? The simplest one is to imagine you have an array,
> `int arr[10];`, and you try to set `arr[11] = 11;`. **The compiler won't
> warn you about it in any non-trivial case.** However this is a memory error, and
> may cause your problem to crash or act weird. Luckily valgrind will report it,
> and even tell you which line of code it's happening on.

I think this is correct. If the code is complicated (non-trivial), the compiler's analysis may not be able to catch an out-of-bounds access. It can only warn you about simple cases.

**Comment by merlinyx** [comment]
Oh that makes sense! Thank you for explaining this!
