### ISSUE TITLE
memory-pointers: strncpy example contains uninitialized reads

### ISSUE THREAD

**Issue by kevin1** [cs3157/recitations#123]
```c
strncpy(d, "456", 2); 
```

does not zero-terminate after copying "45" into d

**Comment by kevin1** [comment]
Holy crap, this has been in the recitation notes since I was a freshman: 57aca52d2a329ef7c38b6c309267a0858a13d33c

**Comment by j-hui** [comment]
was this fixed?

**Comment by j-hui** [comment]
whoops. was going to ask, any progress on this? I can work on this too

**Comment by kevin1** [comment]
Haven’t looked at this problem
