### ISSUE TITLE
Bits- Typos and Doubt

### ISSUE THREAD

**Issue by abhigenie92** [cs3157/recitations#131]
https://github.com/cs3157/recitations/blob/master/D-Bits-Binary-C-Basics/bits-and-binary.md
Typos:
1. Shouldn't it be first "six" instead of "five" letter of alphabet?
2. In bitwise NOT ~, it takes "one" integer as operand. 

Doubts:
1. In bitwise OR I, can the section include why we can't arrive at the same permission in more than 1 way?

**Comment by j-hui** [comment]
Good catches Abhishek!

For your doubt, can you elaborate on what you mean? Or can you provide an example?
