### ISSUE TITLE
Show with/without debugging symbols example

### ISSUE THREAD

**Issue by chmullig** [cs3157/recitations#22]
In OH someone was having issues with their program, and they didn't find valgrind helpful. Well it turns out they were manually running `gcc whatever.c` and then just running `./a.out` for testing. "I'll get to the makefile later." Of course without adding `-g` there were no debugging symbols, so the valgrind errors just had random hex garbage.

This suggests we should more comprehensively show an example of how much debugging symbols (and warnings) can help. Perhaps combine with the gdb example?

**Comment by cjubb39** [comment]
I think this was integrated into the GDB notes (I).  I'll let someone reopen this issue if those notes are not sufficient.
