### ISSUE TITLE
Diagram for smartpointer, other improvements

### ISSUE THREAD

**Issue by chmullig** [cs3157/recitations#42]
Need a diagram for smart pointer illustrating memory.

Should probably explain much more. Including why the count needs to be on the heap.

**Comment by cjubb39** [comment]
I made two sets of diagrams (in PNG and GIF form): one with `count` on heap and one with `count` on stack.

I'll make a basic edit that includes them and leave them available [here] (http://www.cs.columbia.edu/~ecj2122/ta/3157/smart_pointer_diagram.tar.gz) for whoever does a rewrite.

**Comment by cjubb39** [comment]
#43 adds diagrams and includes (very) basic explanation of using pointer for `count`.
