### ISSUE TITLE
Incorporate Chae's .gifs in O-Smart-Pointer/code/ into recitation note O

### ISSUE THREAD

**Issue by ohEmily** [cs3157/recitations#46]
Right now the gifs are sort of separate. It would be nice if we could reference and include them in the recitation note. Right now many students might not see the .gif or might struggle with understanding the animation.

**Comment by kaitlinhuben** [comment]
We actually debated this earlier and thought the gifs would be too
distracting directly in the notes, but I can see a case being made for
putting them back.

**Comment by ohEmily** [comment]
That's a good point. How would you feel about a separate mini note with an
explanation as to what the gifs mean?

**Comment by kaitlinhuben** [comment]
SGTM

Kaitlin Huben
kaitlin.huben@gmail.com
