### ISSUE TITLE
File descriptor vs. FILE pointer distinction needs to be made

### ISSUE THREAD

**Issue by cjubb39** [cs3157/recitations#55]
The section in Notes K on FILE pointers and file descriptors needs to be rewritten.  It's a jumbled mess that doesn't make the proper distinction between a file descriptor (the integer used by `write`, etc.) and a FILE pointer (the FILE * type used by `fwrite`, etc.).

This is a super confusing topic for students and our recitation notes need to be correct and precise.  I don't have time to do it right now, but fixing this should be a very high priority.

**Comment by ohEmily** [comment]
:+1:  awesome!

**Comment by cjubb39** [comment]
Fixed in #56. Turns out I did in fact have time to do it.
