### ISSUE TITLE
Missing IPC material

### ISSUE THREAD

**Issue by j-hui** [cs3157/recitations#64]
Dead link in [J-Fork-Exec notes, section about "Communicating Between Processes"](https://github.com/cs3157/recitations/blob/master/J-Fork-Exec/fork-exec.md#communicating-between-processes), couldn't find any material on IPC in any of the notes

**Comment by kevin1** [comment]
looks like @kaitlinhuben wrote that line

**Comment by danhcole** [comment]
It's the start of Note L

**Comment by j-hui** [comment]
seems to be fixed
