### ISSUE TITLE
Makefile: myadd example shouldn't include arguments to main() 

### ISSUE THREAD

**Issue by kevin1** [cs3157/recitations#83]
The myadd program in the makefile recitation has int argc, char **argv even though we have not covered it in class at this point. We found this after a student came to Jae's office hours confused about what it meant. 

https://github.com/cs3157/recitations/blob/95bfc0042b438c41787528aea186f16d65e93b82/B-Makefiles/practice/myadd/main.c

**Comment by garymlin** [comment]
I'll take care of this.

**Comment by garymlin** [comment]
PR: https://github.com/cs3157/recitations/pull/84
