### ISSUE TITLE
Is the following block of code not ok because of the difference in handling negative numbers from different OS?

### ISSUE THREAD

**Issue by yumyumqing** [cs3157/recitations#90]
size_t x = 5;
size_t y = 3;
int z = y - x;

-- reported as requested by Kevin during OH

**Comment by freedomsworder** [comment]
Sorry but which recitation note was this?

**Comment by yumyumqing** [comment]
Hi Andy,

It’s Note K, the file I/O one.

Happy New Year!

Yanqing

On Jan 1, 2017, at 10:56, Andy Lianghua Xu <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry but which recitation note was this?
